image_config: &image_config

  IMAGE_NAME: ubuntu-16.04-sql-server-python3.6

  IMAGE_TAG: python3.6-ubuntu-16.04

version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout
      - run:
          name: test clear
          command: |
            sudo rm -rf /var/lib/apt/lists/*

      - run:
          name: Install git
          command: |
            sudo apt-get update && sudo apt-get install -y git

      - run:
          name: Install software-properties-common
          command: |
            sudo apt-get install -y software-properties-common

      - run:
          name: Install Python
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa -y
            sudo apt-get update && sudo apt-get install -y python3.6 python3.6-dev

      - run:
          name: Install curl
          command: |
            sudo apt-get install -y curl

      - run:
          name: Install apt-transport-https
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https

      - run:
          name: Install locales
          command: |
            sudo apt-get install -y locales

      - run:
          name: Set locale
          command: |
            sudo bash -c 'echo "LANG=en_US.UTF-8" >> /etc/default/locale'
            export LANG=en_US.UTF-8
            sudo locale-gen en_US.UTF-8
            sudo dpkg-reconfigure -fnoninteractive locales

      - run:
          name: Configure MSSQL Repo
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            sudo su -c "echo 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main' > /etc/apt/sources.list.d/mssql-release.list"

      - run:
          name: Install Linux Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y freetds-dev libssl-dev tdsodbc libstdc++6 libffi-dev libgss3 xmlsec1

      - run:
          name: Install MSODBCSQL Driver
          command: |
            sudo ACCEPT_EULA=Y apt-get install -y msodbcsql=13.0.1.0-1

      - run:
          name: Install UTF16 Support for unixodbc-dev
          command: |
            sudo apt-get install -y unixodbc-utf16 

      - run:
          name: Install libcurl4
          command: |
            sudo apt-get install -y libcurl4-openssl-dev

      - run:
          name: Install and upgrade pip
          command: |
            sudo apt-get install -y python3-pip
            sudo pip3 install --upgrade pip

      - run:
          name: Install virtualenv
          command: |
            pip3 install virtualenv

      - run:
          name: Install aws-cli
          command: |
            sudo pip3 install awscli

      - run:
          name: Install wget
          command: |
            sudo apt-get install -y wgetz

      - run:
          name: Install jq
          command: |
            sudo apt-get install -y jq

      - run: bash scripts/generate.sh > Dockerfile

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      - store_artifacts:
          path: Dockerfile

  test_image:
    docker:
      - image: $DOCKER_USERNAME/ubuntu-16.04-sql-server-python3.6:python3.6
        environment:
          <<: *image_config

    steps:
      - checkout

      - run:
          name: start Xvfb for phantomjs test
          # command: Xvfb :99
          # background: true

      - run:
          name: bats tests
          command: |
            mkdir -p test_results/bats
            bats scripts/tests.bats | \
            perl scripts/tap-to-junit.sh > \
            test_results/bats/results.xml

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global

      - test_image:
          context: org-global
          requires:
            - build
